services:
  database:
    container_name: wiki-pg
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
